apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-depl
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      volumes:
      - name: "client-tls-certs"
        secret:
          secretName: "nats-client-tls-certs"
      containers:
      - name: hello-svc
        command: ["/hello-svc"]
        image: hub.docker.com/syedomair/hello-svc
        env:
        imagePullPolicy: Never
        ports:
        - name: hello-svc
          containerPort: 8180

---

apiVersion: v1
kind: Service
metadata:
  name: hello-srvc
spec:
  type: NodePort
  selector:
    app: roles
  ports:
  - port: 8180
    targetPort: hello-svc
